fixtures:
  symlinks:
    graphite: "#{source_dir}"
  repositories:
    docker_systemd: "https://github.com/ajsmith/puppet-docker_systemd.git"
  forge_modules:
    stdlib:
      repo: "puppetlabs/stdlib"
      ref:  "4.5.1"
    mysql:
      repo: "puppetlabs/mysql"
      ref:  "3.6.2"
