name        'ajsmith-graphite'
version     '0.3.0'
source      'https://github.com/ajsmith/puppet-graphite.git'
author      'Alex Smith <alex.smith@redhat.com>'
license     'GPL-2'
summary     'Graphite monitoring system configuration.'
description 'Graphite monitoring system configuration.'

dependency 'puppetlabs/stdlib', '>=4.5.1'
dependency 'puppetlabs/mysql', '>=3.3.0'
